# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        BlogBundle\Entity\User:
            algorithm: bcrypt
            #Utilitzem aquesta pagina per encriptar
            #https://www.dailycred.com/article/bcrypt-calculator
            cost: 4
            #nombre de xifrats

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: BlogBundle:User
                property: email
                #email va a ser el username per logejar-se

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /login
                #quan sortim de sessió ens redirigirà a login o al que posem a target
                
            
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
