login:
    path: /login
    defaults: { _controller: BlogBundle:User:login }
login:
    path: /login_check

logout: 
    path: /login
    
blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
